"""
investment_debate.py — AI analyst-debate layer for the Investment Analysis
feature. Researched from TauricResearch/TradingAgents and virattt/
ai-hedge-fund (see the plan): analyst reads -> bull/bear debate (with
rebuttals) -> judge, each step grounded in already-computed numbers handed in
by the caller (investment_api.py) — never free-form, never inventing figures.
Explicitly decision-support, not investment advice, same framing both
reference projects use.

Provider-agnostic on purpose (OpenAI/Groq/Mistral are all OpenAI-compatible
chat-completions APIs), so different callers can use different PROVIDERS
entries without rebuilding this module. Company Analysis uses "openai_deep"
(gpt-4.1); the IPO verdict uses "openai" (gpt-4o-mini). Groq is the default
reserved for the Stock Scanner's future bulk shortlist runs.

Isolation: no imports from broker.py/cas_broker.py/config.py — reads its
own provider keys straight from os.environ (already loaded by whatever
process starts this, same .env every other credential in this app uses).
"""
import os
import re
import json
import time
import logging
from concurrent.futures import ThreadPoolExecutor
from typing import Optional

import requests

import investment_valuation as valuation

logger = logging.getLogger(__name__)

PROVIDERS = {
    "groq": {
        "base_url": "https://api.groq.com/openai/v1/chat/completions",
        "env_key": "GROQ_API_KEY",
        # gpt-oss models are reasoning-style — they spend tokens on hidden
        # reasoning before the visible answer, so max_tokens needs real
        # headroom, not just enough for the final text.
        "model": "openai/gpt-oss-20b",
        "max_tokens": 1500,
    },
    "openai": {
        "base_url": "https://api.openai.com/v1/chat/completions",
        "env_key": "OPENAI_API_KEY",
        "model": "gpt-4o-mini",
        "max_tokens": 1400,  # the IPO verdict schema (dual listing-gain/long-term views) is the biggest single call
    },
    "mistral": {
        "base_url": "https://api.mistral.ai/v1/chat/completions",
        "env_key": "MISTRAL_API_KEY",
        "model": "mistral-small-latest",
        "max_tokens": 900,
    },
    # Company Analysis's invest-now-or-wait debate: a much stronger model than
    # gpt-4o-mini, because the task is genuine multi-factor reasoning (a
    # steel-manned bull vs bear, rebuttals, a judge) over a large evidence
    # pack — gpt-4.1 follows long structured instructions reliably and has no
    # hidden-reasoning latency, so a 4-round debate stays around a minute.
    "openai_deep": {
        "base_url": "https://api.openai.com/v1/chat/completions",
        "env_key": "OPENAI_API_KEY",
        "model": "gpt-4.1",
        "max_tokens": 1500,
        "timeout": 120,
        "json_mode": True,
    },
}

DEFAULT_PROVIDER = "groq"

DISCLAIMER = "Findings and recommendations are generated by AI. Please do your own research before investing."


class DebateUnavailable(Exception):
    """Raised when no configured provider has a usable key — callers
    should degrade gracefully (show the quantitative data without the
    debate section), never crash the whole Company Analysis response."""


def _call_llm(prompt: str, system: str, provider: str = DEFAULT_PROVIDER, max_tokens: Optional[int] = None) -> str:
    cfg = PROVIDERS.get(provider)
    if not cfg:
        raise DebateUnavailable(f"unknown provider '{provider}'")
    key = os.environ.get(cfg["env_key"])
    if not key:
        raise DebateUnavailable(f"{cfg['env_key']} not set")

    body = {
        "model": cfg["model"],
        "messages": [{"role": "system", "content": system}, {"role": "user", "content": prompt}],
        "max_tokens": max_tokens or cfg["max_tokens"],
        "temperature": 0.3,  # grounded analysis, not creative writing
    }
    if cfg.get("json_mode"):
        body["response_format"] = {"type": "json_object"}

    r = None
    for attempt in range(2):  # one retry on rate-limit / transient upstream errors
        r = requests.post(cfg["base_url"], headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
                          json=body, timeout=cfg.get("timeout", 45))
        if r.status_code in (429, 500, 502, 503, 504) and attempt == 0:
            time.sleep(3)
            continue
        break
    if r.status_code != 200:
        raise DebateUnavailable(f"{provider} returned {r.status_code}: {r.text[:200]}")
    data = r.json()
    try:
        return data["choices"][0]["message"]["content"]
    except (KeyError, IndexError) as e:
        raise DebateUnavailable(f"{provider} response missing content: {e}")


_JSON_BLOCK_RE = re.compile(r"\{.*\}", re.DOTALL)


def _parse_json_response(text: str) -> dict:
    """LLMs sometimes wrap JSON in prose or code fences despite instructions
    — pull out the first {...} block rather than failing outright."""
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    m = _JSON_BLOCK_RE.search(text)
    if m:
        try:
            return json.loads(m.group(0))
        except json.JSONDecodeError:
            pass
    raise DebateUnavailable(f"could not parse JSON from model response: {text[:200]}")


def summarize_price_momentum(price_history: dict) -> dict:
    """Pure function: turns bse_client's raw daily rows into the compact
    stats the analyst-reads step actually needs (not raw candles — the
    model should reason over summary numbers, same 'grounded in
    already-computed numbers' principle as the Piotroski/Altman scores)."""
    rows = price_history.get("rows", []) if price_history else []
    closes = []
    for row in rows:
        try:
            closes.append(float(str(row.get("vale1", "")).replace(",", "")))
        except (TypeError, ValueError):
            continue
    if not closes:
        return {"available": False}

    latest = closes[-1]

    def pct_change_over(n_bars):
        if len(closes) <= n_bars:
            return None
        base = closes[-n_bars - 1]
        return round(((latest - base) / base) * 100, 2) if base else None

    return {
        "available": True,
        "latest_close": latest,
        "pct_change_1m": pct_change_over(21),
        "pct_change_3m": pct_change_over(63),
        "pct_change_6m": pct_change_over(126),
        "pct_change_12m": pct_change_over(min(251, len(closes) - 1)),
        "period_high": max(closes),
        "period_low": min(closes),
        "pct_off_period_high": round(((latest - max(closes)) / max(closes)) * 100, 2),
    }


def _clamp_star_rating(parsed: dict) -> int:
    """The model doesn't reliably keep star_rating consistent with its own
    long_term_view/confidence despite the prompt asking for it (observed
    5-star ratings alongside an 'avoid' long-term call on real RHPs) — so
    it's clamped deterministically here rather than trusted as-is."""
    try:
        rating = int(parsed.get("star_rating") or 3)
    except (TypeError, ValueError):
        rating = 3
    rating = max(1, min(5, rating))
    long_term = parsed.get("long_term_view")
    listing_gain = parsed.get("listing_gain_view")
    if long_term == "avoid" and listing_gain == "avoid":
        rating = min(rating, 2)
    elif long_term == "avoid":
        rating = min(rating, 3)
    elif long_term == "neutral":
        rating = min(rating, 4)
    return rating


def run_ipo_verdict(mechanics: dict, sentiment: dict, rhp_data: dict, scores: dict, trend: dict,
                     investor_interest: str, provider: str = DEFAULT_PROVIDER) -> dict:
    """IPO Review's verdict step — deliberately different from
    run_full_debate above: the user explicitly wants a final, readable
    decision with reasons, not the hedged never-say-buy-or-sell framing
    used for listed-company Company Analysis.

    Two separate calls, not one: real IPO commentary (the kind this was
    modelled on) almost always splits 'apply for the listing pop' from
    'worth holding long-term' — the first is driven by GMP/subscription/
    pricing, the second by fundamentals. An earlier version used a single
    fundamentals-first verdict and it came back 'avoid' on nearly
    everything, because growth-stage pre-IPO companies routinely score
    weak on Piotroski/Altman (negative working capital, heavy capex) even
    when genuinely growing and in high demand — that's a real difference
    between the two calls, not a bug to average away into one number.

    Still grounded only in the data handed in (RHP-extracted risk factors
    and restated financials, the Piotroski/Altman-Z' scores and YoY trend
    computed from them, and the GMP/subscription/P-E sentiment read) and
    still carries the disclaimer — this is a single AI-generated read to
    support the user's own research, not a substitute for it."""
    payload = {
        "company": mechanics.get("scrip_name"), "price_band": mechanics.get("price_band"),
        "issue_size_shares": mechanics.get("issue_size_shares"),
        "objects_of_offer": rhp_data.get("objects_of_offer"),
        "top_risk_factors": [r.get("heading") for r in (rhp_data.get("risk_factors") or [])[:12]],
        "revenue_yoy_pct": trend.get("revenue_yoy_pct"), "revenue_direction": trend.get("revenue_direction"),
        "net_profit_yoy_pct": trend.get("net_profit_yoy_pct"), "net_profit_direction": trend.get("net_profit_direction"),
        "piotroski_f_score": scores.get("piotroski"),
        "altman_zprime_score": scores.get("altman_zprime"),
        "market_sentiment": sentiment,
        "investor_interest": investor_interest,
    }
    system = (
        "You are an IPO analyst producing the kind of read retail investors act on: a star rating, a "
        "short-term listing-gain call, and a separate long-term hold call. Cite specific numbers from the "
        "JSON data given — never invent a figure not in it. If a field is missing/null, say so rather than "
        "guessing.\n\n"
        "LISTING-GAIN VIEW (apply/avoid/neutral): this is primarily about GMP %, subscription demand "
        "(investor_interest), and how the issue is priced (P/E in market_sentiment.gmp.pe_ratio if present) "
        "— NOT about long-term fundamental quality. A company can have a weak Piotroski/Altman score and "
        "still be a reasonable listing-gain 'apply' if GMP and subscription are strong, because that score "
        "reflects a young/growth-stage balance sheet (heavy capex, negative working capital from scaling), "
        "not distress — do not let it override a clearly positive market signal here. This must NOT default "
        "to 'apply' — weigh GMP % and investor_interest TOGETHER, not GMP alone: strong GMP (roughly 10%+) "
        "with moderate-or-better investor_interest is a genuine apply; low/negative GMP, or decent GMP paired "
        "with LOW investor_interest (weak subscription despite the premium — a real warning sign, not just "
        "noise), should come back 'avoid' or 'neutral', not 'apply'. State the expected listing-gain range "
        "implied by the GMP % explicitly in listing_gain_reason (e.g. 'GMP of 18% implies ~18%+ listing "
        "gains') when GMP is available and the call is 'apply'.\n\n"
        "LONG-TERM VIEW (invest/avoid/neutral): this IS primarily about fundamentals — the Piotroski/Altman "
        "scores, revenue/profit trend direction, risk factors, and objects of the offer — weighted more "
        "heavily than sentiment, since sentiment is unofficial and can reverse before listing.\n\n"
        "You MUST reach a clear call on both — do not hedge into a non-answer on either. Respond with ONLY "
        "valid JSON: {"
        "\"star_rating\": 1-5 (overall — must be consistent with the two views below: don't give 4-5 stars "
        "if long_term_view is 'avoid' or key financial data is missing/null; reserve 4-5 for when both "
        "views are positive AND the data backing them is reasonably complete), "
        "\"business_summary\": \"1 sentence on what the company actually does, inferred from the risk "
        "factors/objects of offer given — describe the business, don't invent financial specifics\", "
        "\"listing_gain_view\": \"apply\"|\"avoid\"|\"neutral\", "
        "\"listing_gain_reason\": \"1-2 sentences citing GMP %, subscription, and/or pricing\", "
        "\"long_term_view\": \"invest\"|\"avoid\"|\"neutral\", "
        "\"long_term_reason\": \"1-2 sentences citing fundamentals/risk factors\", "
        "\"issue_price_assessment\": \"attractive\"|\"reasonable\"|\"aggressive\", "
        "\"issue_price_reason\": \"1 sentence, citing the P/E if available, else say P/E unavailable\", "
        "\"confidence\": \"low\"|\"medium\"|\"high\", "
        "\"confidence_score\": 0-100 (lower when fields are missing/null or the two views conflict sharply), "
        "\"fundamental_read\": \"3-5 sentences on financial quality, YoY trend, and risk factors, citing numbers\", "
        "\"sentiment_read\": \"1-3 sentences on GMP/subscription strength\", "
        "\"key_reasons\": [\"3-5 short bullet reasons, most important first\"], "
        "\"reasoning\": \"2-4 sentences explaining how the listing-gain and long-term views were weighed\"}."
    )
    prompt = f"Data:\n{json.dumps(payload, default=str)}\n\nProduce the verdict."
    try:
        raw = _call_llm(prompt, system, provider)
        parsed = _parse_json_response(raw)
        parsed["star_rating"] = _clamp_star_rating(parsed)
        return {"available": True, "provider": provider, **parsed, "disclaimer": DISCLAIMER}
    except DebateUnavailable as e:
        logger.warning(f"investment_debate: IPO verdict unavailable ({provider}): {e}")
        return {"available": False, "reason": str(e), "disclaimer": DISCLAIMER}
    except Exception as e:
        logger.error(f"investment_debate: IPO verdict unexpected failure: {e}")
        return {"available": False, "reason": "unexpected error", "disclaimer": DISCLAIMER}


# ── Company Analysis: "should I invest now, wait, or at what price?" ─────
#
# Four rounds over ONE evidence dossier built by investment_valuation.py
# (fundamentals history, own-history P/E, industry P/E, shareholding trend,
# recent announcements, and a deterministic 5-year scenario model with an
# entry-price ladder). The dossier's numbers are computed in code; the model
# only reasons over them.
#   1. analyst reads (5 lenses)        ┐ run in parallel
#   2. bull opening / bear opening     ┘
#   3. bull rebuttal / bear rebuttal     (each sees the other side's opening)
#   4. judge: weighs the debate, decides, gives the plan
# Bull and bear get an IDENTICAL structure and evidence standard on purpose —
# four numbered arguments, each backed by a cited figure, plus an admitted
# weak spot — so neither side can win by being longer or vaguer.

_GROUNDING = (
    "You are given an evidence dossier (JSON) about one listed Indian company, including "
    "'valuation_model': a deterministic 5-year scenario model (bear/base/bull annual returns "
    "if bought at today's price), an entry-price ladder, and a baseline stance. Rules: cite "
    "specific figures from the dossier; NEVER invent a number, event, news item or price level "
    "that is not in it; if something is missing, say it is missing. Prices are in ₹; financial "
    "statement figures are ₹ crore. If valuation_model.reliability.level is 'low' or 'medium', "
    "say so plainly and lower your certainty accordingly. The valuation model is the SHARED yardstick "
    "both sides are measured against: you may quote its scenario returns and price levels as evidence, "
    "but never argue that 'the model is reliable/accurate' as a point in itself. Do not quote macro "
    "figures (inflation, bond yields, market returns) that are not in the dossier. ROE in the dossier is "
    "net income / year-end equity and can differ from the ROE shown elsewhere on the page; say which "
    "definition you mean when you cite it. State which quarter the financials run through "
    "(data_freshness.financials_through) at least once; if data_freshness.status is 'tickertape_behind', "
    "say plainly that the fundamentals are one quarter out of date and lower your confidence. Only make a comparison (e.g. 'above its own history', "
    "'well covered by earnings') if BOTH sides of it are actually in the dossier — e.g. a dividend "
    "claim needs payout_ratio_pct, a history claim needs the history. The industry P/E is a sector average and can be a poor "
    "yardstick for diversified or unusual businesses (e.g. conglomerates) — question it where that applies. "
    "Respond with ONLY valid JSON."
)

_LOW_REL_RULES = (
    " LOW-RELIABILITY MODE: valuation_model.reliability.level is 'low' — the numbers a price-based call needs are too "
    "unreliable, so ALL price levels and return projections have been withheld from the dossier. Do NOT state, imply or "
    "estimate any entry price, target price, fair value, price range or expected annual return. Keep the specific data "
    "problems in valuation_model.reliability.reasons in view and say them plainly, in ordinary words. Argue only from "
    "facts that ARE in the dossier: the business, reported earnings and margins, balance sheet, shareholding, "
    "announcements, and the current price relative to its own 52-week range."
)

STANCE_ORDER = ["accumulate_now", "start_small_and_stagger", "wait_for_better_price", "avoid_for_now"]


def _dossier_json(dossier: dict) -> str:
    return json.dumps(dossier, default=str, separators=(",", ":"))


def _run_reads(dossier: dict, provider: str, low_rel: bool = False) -> dict:
    system = (
        "You are a senior equity analyst. " + _GROUNDING + " Produce five reads, each 3-5 sentences "
        "with cited numbers, no filler: "
        '{"business_quality": "what the business is (from company.business), margins, ROE, cash '
        "conversion, leverage, Piotroski/Altman (respect quality_scores.note if present)\", "
        '"growth_and_earnings": "EPS/revenue CAGRs, consistency (eps_up_years_of_last_5), latest-quarter '
        "YoY versus the multi-year trend, and whether growth is accelerating or slowing\", "
        '"valuation": "three lenses - versus its industry (pe_premium_to_industry_pct, P/B, dividend '
        "yield), versus ITS OWN history (own_history_pe median and current_percentile_of_history), and "
        "the scenario model's expected annual return at today's price; conclude cheap/fair/expensive\", "
        '"sentiment_and_flows": "price trend (52-week position, momentum), shareholding shifts (FII/DII/'
        "mutual funds/promoter/pledge) and any material announcements actually listed; say so if nothing "
        "material\", "
        '"risks_and_unknowns": "the specific things that could break the thesis for THIS company, plus '
        "what this data cannot tell us and the valuation model's reliability caveats\"}"
    )
    if low_rel:
        system += _LOW_REL_RULES + " For the 'valuation' read: say plainly that no valuation call is possible for this company and why."
    return _parse_json_response(_call_llm(f"Dossier:\n{_dossier_json(dossier)}", system, provider, max_tokens=1500))


def _run_opening(side: str, dossier: dict, provider: str, low_rel: bool = False) -> dict:
    is_bull = side == "bull"
    stance = (
        "the strongest possible advocate FOR buying this stock at today's price" if is_bull
        else "the strongest possible advocate AGAINST buying this stock at today's price"
    )
    scenario = "bull" if is_bull else "bear"
    system = (
        f"You are {stance}. Steel-man your side - make the best honest case a top analyst could - "
        "but use only facts in the dossier. " + _GROUNDING + " Give EXACTLY four arguments, strongest "
        "first, each with a cited figure - the other side is held to the identical standard. Schema: "
        '{"thesis": "one sentence", "arguments": [{"headline": "max 12 words", "evidence": "the specific '
        'figures from the dossier", "why_it_matters": "1-2 sentences linking it to returns or risk"}, ... x4], '
        f'"what_must_be_true": "1-2 sentences: the assumptions your case needs, and the valuation_model '
        f"{scenario}-scenario annual return at today's price (quote it)\", "
        '"own_weak_spot": "the single most honest weakness in YOUR case", '
        '"invalidation": "one specific, observable signal (a number, level or event) that would prove your side wrong"}'
    )
    if low_rel:
        system += (_LOW_REL_RULES + " In what_must_be_true describe only what would need to be true about the business and its "
                   "earnings (no price or return figures), and make invalidation an observable business or data event, not a price.")
    return _parse_json_response(_call_llm(f"Dossier:\n{_dossier_json(dossier)}", system, provider, max_tokens=1600))


def _run_rebuttal(side: str, dossier: dict, own_opening: dict, opp_opening: dict, provider: str, low_rel: bool = False) -> dict:
    other = "bear" if side == "bull" else "bull"
    system = (
        f"You are the {side.upper()} advocate in an investment debate. You have read the {other.upper()} "
        "advocate's opening. " + _GROUNDING + " Answer their TWO strongest arguments directly: quote what "
        "they claim, respond with evidence and figures from the dossier, and concede whatever part is "
        "genuinely fair - a rebuttal that concedes nothing is not credible. Schema: "
        '{"rebuttals": [{"their_point": "...", "your_response": "...", "concession": "..."}, {...}], '
        '"updated_position": "1-2 sentences: what, if anything, changed in your view after hearing them - do not just repeat your opening"}'
    )
    if low_rel:
        system += _LOW_REL_RULES
    prompt = (f"Dossier:\n{_dossier_json(dossier)}\n\nYOUR opening:\n{json.dumps(own_opening, default=str)}\n\n"
              f"THEIR ({other}) opening:\n{json.dumps(opp_opening, default=str)}")
    return _parse_json_response(_call_llm(prompt, system, provider, max_tokens=1200))


def _judge_system_low_reliability() -> str:
    return (
        "You chair an investment committee. This company's data is too unreliable for a price-based call, and the "
        "investor must be told that plainly. Judge the debate on the merit of the evidence. " + _GROUNDING + _LOW_REL_RULES + "\n\n"
        "Do NOT recommend buying or waiting for any price. Be direct about what is wrong with the data and what that means: "
        "this is a speculative situation, not a valuation case. Schema: "
        '{"headline": "ONE sentence that starts with \'Low-reliability company:\' and states, in plain words, the main data '
        'problems and that no price-based call is possible", '
        '"final_stance": "no_valuation_call", '
        '"stance_reasoning": "3-5 sentences: what can and cannot be concluded, and why the data is unreliable", '
        '"who_argued_better": "bull"|"bear"|"balanced", '
        '"scorecard": [{"issue": "...", "edge": "bull"|"bear"|"even", "why": "1-2 sentences"}, ... x5 covering: '
        "valuation (must say no valuation call is possible and why), durability of growth, quality and balance sheet, "
        "momentum and investor flows, the single biggest risk], "
        '"today_vs_wait": "2-4 sentences: what a cautious person should do with this information - no price targets; '
        'if they are considering it anyway it is speculative; what to verify first", '
        '"how_to_use_price_levels": "one sentence: price levels are withheld for this company because its data is too unreliable to support them", '
        '"what_would_change_my_mind": ["3-4 observable DATA or BUSINESS events (e.g. a full year of profits, a longer reporting history, '
        'debt falling) that would make a valuation possible - no price levels"], '
        '"confidence": "low", "confidence_reason": "one sentence naming the main data problem"}'
    )


def _run_judge(dossier: dict, reads: dict, bull: dict, bear: dict, provider: str, low_rel: bool = False) -> dict:
    baseline = (dossier.get("valuation_model") or {}).get("baseline_stance")
    system = _judge_system_low_reliability() if low_rel else (
        "You chair an investment committee deciding, for a long-term retail investor, whether to invest "
        "in this stock, when, and at what prices. Judge the debate on the merit of the evidence, not on "
        "length or confidence. " + _GROUNDING + "\n\n"
        f"Anchor on valuation_model.baseline_stance ('{baseline}'). Stances, best to worst for a buyer: "
        f"{', '.join(STANCE_ORDER)}. Your final_stance may differ from the baseline by AT MOST ONE step, "
        "and only if you point to specific evidence (earnings momentum, shareholding shifts, announcements, "
        "debate points) that the numeric model does not capture. Be direct - the investor needs an answer, "
        "not hedging. Be honest that no one can predict tomorrow's price: timing within days is noise, and "
        "what a disciplined investor controls is the PRICE PAID relative to value and how capital is staged. "
        "Use ONLY price levels from valuation_model (entry_ladder, bear_case_safe_price, tranche_plan) - "
        "never invent a level. EXCEPTION: if valuation_model.reliability.level is 'low', the model's inputs "
        "are too unreliable to support entry prices — do NOT name any price as a recommended entry in the "
        "headline, today_vs_wait or how_to_use_price_levels; say plainly that the price levels are indicative "
        "only, that this is a speculative situation rather than a valuation call, and keep confidence low. Schema: "
        '{"headline": "one direct sentence answering invest/wait and naming a price from the model", '
        '"final_stance": "one of the four stance keys", '
        '"stance_reasoning": "3-5 sentences", '
        '"who_argued_better": "bull"|"bear"|"balanced", '
        '"scorecard": [{"issue": "...", "edge": "bull"|"bear"|"even", "why": "1-2 sentences with figures"}, ... x5 covering: '
        "valuation, durability of growth, quality and balance sheet, momentum and investor flows, the single biggest risk], "
        '"today_vs_wait": "2-4 sentences answering: invest today, tomorrow, or wait - and why", '
        '"how_to_use_price_levels": "2-3 plain-language sentences on how to use the tranche plan and ladder", '
        '"what_would_change_my_mind": ["3-4 specific observable triggers: price levels from the model, quarterly-result thresholds, shareholding or promoter events"], '
        '"confidence": "low"|"medium"|"high", "confidence_reason": "one sentence (mention model reliability)"}'
    )
    prompt = (f"Dossier:\n{_dossier_json(dossier)}\n\nAnalyst reads:\n{json.dumps(reads, default=str)}\n\n"
              f"BULL case:\n{json.dumps(bull, default=str)}\n\nBEAR case:\n{json.dumps(bear, default=str)}")
    return _parse_json_response(_call_llm(prompt, system, provider, max_tokens=2200))


def _clamp_stance(judge: dict, baseline: Optional[str]) -> dict:
    """The judge may move the baseline stance at most one step — the same
    'don't trust the model to self-enforce' rule as _clamp_star_rating."""
    final = judge.get("final_stance")
    if baseline not in STANCE_ORDER:
        return judge
    if final not in STANCE_ORDER:
        judge["final_stance"], judge["stance_adjusted"] = baseline, False
        return judge
    b, f = STANCE_ORDER.index(baseline), STANCE_ORDER.index(final)
    if abs(f - b) > 1:
        f = b + (1 if f > b else -1)
        judge["final_stance"] = STANCE_ORDER[f]
        judge["stance_clamped_note"] = "The model proposed a larger departure from the numeric baseline than allowed; limited to one step."
    judge["stance_adjusted"] = judge["final_stance"] != baseline
    return judge


def run_deep_debate(dossier: dict, valuation_model: dict, provider: str = "openai_deep") -> dict:
    """Never raises. The numeric valuation_model is always returned, even if
    the AI layer fails — it is useful on its own, and the page must not lose
    it because a provider is rate-limited.

    LOW-RELIABILITY companies: price levels and return projections are removed
    from what the AI sees AND from what the page receives (redact_for_low_
    reliability); the judge runs in a mode that leads with the data problems
    and makes no price-based call; and any rupee figure that still matches a
    withheld model price is scrubbed from the output as a last safety net."""
    if not (valuation_model or {}).get("available"):
        # No numeric basis (no multi-year data, or no positive earnings): a debate
        # over a thin evidence pack would only produce confident-sounding filler,
        # so skip the AI calls entirely — no low-quality answer, and no cost.
        return {"available": False, "ai_skipped": True, "reason": (valuation_model or {}).get("reason", "insufficient data"),
                "valuation_model": valuation_model, "disclaimer": DISCLAIMER, "data_freshness": (dossier or {}).get("data_freshness")}

    low_rel = ((valuation_model or {}).get("reliability") or {}).get("level") == "low"
    withheld = set()
    public_model = valuation_model
    if low_rel:
        public_model, withheld = valuation.redact_for_low_reliability(valuation_model)
        dossier = {**dossier, "valuation_model": public_model}
    base = {"valuation_model": public_model, "disclaimer": DISCLAIMER, "low_reliability": low_rel,
            "data_freshness": (dossier or {}).get("data_freshness")}
    try:
        with ThreadPoolExecutor(max_workers=3) as pool:
            f_reads = pool.submit(_run_reads, dossier, provider, low_rel)
            f_bull = pool.submit(_run_opening, "bull", dossier, provider, low_rel)
            f_bear = pool.submit(_run_opening, "bear", dossier, provider, low_rel)
            reads, bull_open, bear_open = f_reads.result(), f_bull.result(), f_bear.result()
        with ThreadPoolExecutor(max_workers=2) as pool:
            f_br = pool.submit(_run_rebuttal, "bull", dossier, bull_open, bear_open, provider, low_rel)
            f_er = pool.submit(_run_rebuttal, "bear", dossier, bear_open, bull_open, provider, low_rel)
            bull_reb, bear_reb = f_br.result(), f_er.result()
        bull = {"opening": bull_open, "rebuttal": bull_reb}
        bear = {"opening": bear_open, "rebuttal": bear_reb}
        judge = _run_judge(dossier, reads, bull, bear, provider, low_rel)
        if low_rel:
            judge["final_stance"], judge["stance_adjusted"] = "no_valuation_call", False
        else:
            judge = _clamp_stance(judge, (valuation_model or {}).get("baseline_stance"))
        result = {"available": True, "provider": provider, "model_name": PROVIDERS[provider]["model"],
                  "reads": reads, "bull": bull, "bear": bear, "judge": judge, **base}
        return valuation.scrub_withheld_prices(result, withheld) if low_rel else result
    except DebateUnavailable as e:
        logger.warning(f"investment_debate: deep debate unavailable ({provider}): {e}")
        return {"available": False, "reason": str(e), **base}
    except Exception as e:
        logger.error(f"investment_debate: deep debate unexpected failure: {e}", exc_info=True)
        return {"available": False, "reason": "unexpected error", **base}
