"""
Live Bar Processor — runs each strategy's run_backtest() on live frames and
diffs consecutive results to detect new entries/exits.

Architecture:
    BacktestDiffProcessor (base) calls run_backtest(frames) — the EXACT same
    function that produces chart overlay signals.  By diffing consecutive
    backtest results it detects new entries and exits, guaranteeing that live
    signals are **identical** to the backtest / chart overlay.

    Each strategy gets a thin subclass that only specifies:
        - strategy_id   (e.g. "regime_reversal")
        - _get_module() (returns the strategy module with run_backtest())
"""

import logging
import pandas as pd
import numpy as np
from dataclasses import dataclass, field
from typing import List, Optional, Dict

logger = logging.getLogger(__name__)


@dataclass
class LiveSignal:
    """A signal generated by the live bar processor."""
    signal_type: str       # "ENTRY" or "EXIT"
    direction: str         # "LONG" or "SHORT"
    signal: str            # "LONG", "SHORT", "LONG_EXIT", "SHORT_EXIT"
    time: str              # ISO timestamp of the bar
    entry_price: float = 0.0
    sl: float = 0.0
    target1: float = 0.0
    target2: float = 0.0
    exit_price: float = 0.0
    exit_reason: str = ""
    pnl: float = 0.0
    pnl_pts: float = 0.0
    strategy: str = ""
    weighted_score: float = 0.0
    reasons: List[str] = field(default_factory=list)
    macro_bias: str = ""
    adx_1h: float = 0.0
    atr_5m: float = 0.0
    h1_trend: str = ""
    regime: str = ""
    regime_confidence: float = 0.0
    playbook: str = ""
    entry_quality: float = 0.0
    ml_prob: float = 0.0
    rr_t1: float = 0.0
    risk_pts: float = 0.0
    long_score: float = 0.0
    short_score: float = 0.0

    def to_signal_dict(self) -> dict:
        """Convert to dict format compatible with _add_signal_to_history."""
        d = {
            "signal": self.signal,
            "time": self.time,
            "entry": self.entry_price if self.signal_type == "ENTRY" else self.exit_price,
            "close": self.exit_price if self.signal_type == "EXIT" else self.entry_price,
            "sl": self.sl,
            "target1": self.target1,
            "target2": self.target2,
            "strategy": self.strategy,
            "weighted_score": self.weighted_score,
            "reasons": self.reasons,
            "macro_bias": self.macro_bias,
            "adx_1h": self.adx_1h,
            "atr_5m": self.atr_5m,
            "h1_trend": self.h1_trend,
            "ml_prob": self.ml_prob,
            "rr_t1": self.rr_t1,
            "risk_pts": self.risk_pts,
            "long_score": self.long_score,
            "short_score": self.short_score,
            "regime": self.regime,
            "regime_confidence": self.regime_confidence,
            "playbook": self.playbook,
            "entry_quality": self.entry_quality,
        }
        if self.signal_type == "EXIT":
            d["reason"] = self.exit_reason
            d["exit_price"] = self.exit_price
            d["pnl"] = self.pnl
            d["pnl_pts"] = self.pnl_pts
        return d


def _to_ist_iso(ts) -> str:
    """Convert a timestamp to IST ISO string."""
    import pytz
    t = pd.Timestamp(ts)
    if t.tzinfo is None:
        t = t.tz_localize("Asia/Kolkata")
    return t.isoformat()


# Root-cause fix (2026-08-25) for the "stale replay" issue: as the rolling
# 300-bar eval window slides forward, a kernel's own indicator/regime state
# near the window's older edge isn't perfectly stable -- the same historical
# bar can go from "not a trade" to "a trade" between polls purely because the
# window's warm-up context for it changed, with no change in the underlying
# market data. That made the diff below occasionally "discover" a trade from
# days ago and report it as brand new. main.py already had downstream
# age-gates (Telegram, chart) that caught this before it reached the user,
# but the diff itself had no such check, so the same stale rediscovery could
# repeat indefinitely every time the window happened to flicker again.
# STALE_ENTRY_MAX_AGE_MIN is deliberately generous (not the 10-min cutoff
# main.py uses for order execution/alerts) -- normal poll-cycle detection
# latency measured up to ~8 min in practice, and unlike the downstream gates
# (which just skip an alert for an otherwise-still-tracked signal), silently
# dropping the ENTRY here also removes it from consideration forever on the
# next poll. A wide margin protects against ever discarding a genuine signal
# while still comfortably catching rediscoveries that are actually hours to
# days old.
STALE_ENTRY_MAX_AGE_MIN = 60.0


def _bar_age_minutes(bar_time) -> Optional[float]:
    """Age of a bar's own timestamp in minutes, or None if unparseable."""
    try:
        import pytz
        parsed = pd.to_datetime(bar_time)
        if getattr(parsed, "tzinfo", None) is not None:
            parsed = parsed.tz_convert("Asia/Kolkata").tz_localize(None)
        now_naive = pd.Timestamp.now(tz=pytz.timezone("Asia/Kolkata")).tz_localize(None)
        return (now_naive - parsed).total_seconds() / 60.0
    except Exception:
        return None


# ═══════════════════════════════════════════════════════════════════════════════
# GENERIC BACKTEST-DIFF PROCESSOR (base class)
# ═══════════════════════════════════════════════════════════════════════════════

class BacktestDiffProcessor:
    """Runs run_backtest(frames) and diffs consecutive results.

    Subclasses must set:
        strategy_id  – e.g. "regime_reversal"
    and implement:
        _get_module() – return the strategy module with run_backtest()
    """

    strategy_id: str = ""

    def __init__(self):
        self._prev_trade_keys: set = set()
        self._prev_open_key: Optional[tuple] = None
        self._initialised = False
        self.position = "NONE"
        self.trade_source = "NONE"
        self.entry_price = 0.0
        self.sl = 0.0
        self.target1 = 0.0
        self.target2 = 0.0
        self._last_atr = 0.0
        self._last_close = 0.0
        self._entry_signal_detail: Optional[dict] = None
        self._last_exit_signal: Optional[str] = None
        self._last_exit_reason: Optional[str] = None
        self._regime = "SIDEWAYS"
        self.last_processed_ts = None

    def _get_module(self):
        """Return the strategy module that has run_backtest(). Override in subclass."""
        raise NotImplementedError

    def reset(self):
        """Reset all state — call on daily boundary or restart."""
        self._prev_trade_keys = set()
        self._prev_open_key = None
        self._initialised = False
        self.position = "NONE"
        self.trade_source = "NONE"
        self.entry_price = 0.0
        self.sl = 0.0
        self.target1 = 0.0
        self.target2 = 0.0
        self._last_atr = 0.0
        self._last_close = 0.0
        self._entry_signal_detail = None
        self._last_exit_signal = None
        self._last_exit_reason = None
        self._regime = "SIDEWAYS"
        self.last_processed_ts = None
        logger.info(f"[{self.strategy_id}] Processor state reset")

    # ──────────────────────────────────────────────────────────────────
    #  CORE: run backtest, diff trades, emit LiveSignal objects
    # ──────────────────────────────────────────────────────────────────
    def _get_kernel(self):
        """Return registered StrategyKernel for this strategy."""
        try:
            from strategy_kernel import get_kernel
            return get_kernel(self.strategy_id)
        except Exception:
            return None

    def process_frames(self, frames: dict, cfg, lot_size: int = 30) -> List[LiveSignal]:
        # Validate minimum data
        required = ["5", "15", "60", "1D"]
        for r in required:
            if r not in frames or frames[r] is None or len(frames[r]) < 30:
                return []

        # Check if 5m candle timestamp has changed — skip redundant evaluation if unchanged
        if "5" in frames and not frames["5"].empty:
            current_5m_ts = frames["5"].iloc[-1].get("timestamp")
            if self._initialised and self.last_processed_ts == current_5m_ts:
                return []

        # Slice frames to trailing window (N=300) for fast live bar evaluation
        eval_frames = {}
        for tf, df in frames.items():
            if df is not None and not df.empty:
                eval_frames[tf] = df.tail(300).copy() if len(df) > 300 else df
            else:
                eval_frames[tf] = df

        # Run kernel backtest
        kernel = self._get_kernel()
        if kernel is None:
            logger.error(f"CRITICAL: StrategyKernel for '{self.strategy_id}' not registered in strategy registry!")
            return []
        try:
            result = kernel.safe_run_backtest(eval_frames)
        except Exception as e:
            logger.error(f"[{self.strategy_id}] Strategy evaluation failed: {e}", exc_info=True)
            return []

        if not result or "error" in result:
            logger.debug(f"[{self.strategy_id}] Backtest returned: {result}")
            return []

        bt_trades = result.get("trades", [])
        stats = result.get("stats", {})
        qty = lot_size

        # Update regime from stats
        regime_dist = stats.get("regime_distribution", {})
        if regime_dist:
            self._regime = max(regime_dist, key=regime_dist.get)

        # Update last close / ATR from 5m frame
        if "5" in frames and not frames["5"].empty:
            last_bar = frames["5"].iloc[-1]
            self._last_close = float(last_bar.get("close", 0))
            atr_v = float(last_bar.get("atr", 0))
            self._last_atr = atr_v if atr_v > 5 else self._last_close * 0.002
            self.last_processed_ts = last_bar.get("timestamp")

        # ── First call: snapshot state, suppress signals ──
        # Track _prev_open_key for diff detection but do NOT set
        # self.position — we only show positions from actual new signals,
        # never from inherited backtest state (avoids phantom positions).
        if not self._initialised:
            self._initialised = True
            self._prev_trade_keys = {(t["direction"], t["entry_time"]) for t in bt_trades}
            self._prev_open_key = None
            for t in reversed(bt_trades):
                if t.get("exit_reason") == "OPEN" and not t.get("exit_time"):
                    self._prev_open_key = (t["direction"], t["entry_time"])
                    break
            logger.info(
                f"[{self.strategy_id}] Initialised from backtest: "
                f"{len(bt_trades)} trades, open_key={'yes' if self._prev_open_key else 'no'}, regime={self._regime}"
            )
            return []

        # ── Diff: detect new entries and exits ──
        signals_out: List[LiveSignal] = []
        current_keys = set()
        current_open_key = None

        for t in bt_trades:
            key = (t["direction"], t["entry_time"])
            current_keys.add(key)

            # NOTE: deliberately NOT also checking `not t.get("exit_time")` here.
            # safe_run_backtest() pipes every trade through
            # format_and_enrich_backtest_result(), which coerces a still-open
            # trade's empty exit_time ("") into the literal string "-" (truthy) —
            # combining that with exit_reason=="OPEN" made is_open permanently
            # False for every genuinely-open live position, which fired a
            # spurious same-batch EXIT right behind every ENTRY and then made
            # the position invisible to _prev_open_key tracking forever after.
            # exit_reason survives enrichment unchanged, so it alone is a
            # reliable signal of "still open".
            is_open = t.get("exit_reason") == "OPEN"
            if is_open:
                current_open_key = key

            # Was the previous open trade now closed?
            if key == self._prev_open_key and not is_open:
                signals_out.append(self._exit_from_trade(t, qty))
                logger.info(
                    f"[{self.strategy_id}] EXIT {t['direction']} "
                    f"reason={t.get('exit_reason')} @ {t.get('exit_price', 0)}"
                )

            # New trade not seen before? Only trust it as a genuine live
            # signal if its own bar is recent -- a "new" trade whose entry
            # is actually old is a rediscovered rolling-window artifact, not
            # real news (see STALE_ENTRY_MAX_AGE_MIN above). current_keys
            # already includes it either way, so it's folded into known
            # state and never reconsidered again regardless.
            if key not in self._prev_trade_keys:
                _age = _bar_age_minutes(t["entry_time"])
                if _age is not None and _age > STALE_ENTRY_MAX_AGE_MIN:
                    logger.info(
                        f"[{self.strategy_id}] Suppressed stale rediscovered "
                        f"{t['direction']} entry_time={t['entry_time']} "
                        f"age={_age:.1f}m (not emitted as live signal)"
                    )
                else:
                    signals_out.append(self._entry_from_trade(t))
                    logger.info(
                        f"[{self.strategy_id}] ENTRY {t['direction']} "
                        f"@ {t.get('entry_price', 0)} SL={t.get('sl', 0)} "
                        f"source={t.get('source', '?')}"
                    )
                    # If already closed on the same bar, also emit exit
                    if not is_open and t.get("exit_time"):
                        signals_out.append(self._exit_from_trade(t, qty))
                        logger.info(
                            f"[{self.strategy_id}] Immediate EXIT {t['direction']} "
                            f"reason={t.get('exit_reason')} (same bar)"
                        )

        # ── Update internal state ──
        self._prev_trade_keys = current_keys
        self._prev_open_key = current_open_key

        if current_open_key:
            for t in reversed(bt_trades):
                if (t["direction"], t["entry_time"]) == current_open_key:
                    self.position = t["direction"]
                    self.entry_price = t.get("entry_price", 0)
                    self.sl = t.get("sl", 0)
                    self.target1 = t.get("target1", 0)
                    self.target2 = t.get("target2", 0)
                    self.trade_source = t.get("source", "REGIME")
                    self._last_exit_signal = None
                    self._last_exit_reason = None
                    break
        else:
            if self.position != "NONE":
                last_closed = bt_trades[-1] if bt_trades else None
                if last_closed and last_closed.get("exit_time"):
                    self._last_exit_signal = (
                        "LONG_EXIT" if last_closed["direction"] == "LONG" else "SHORT_EXIT"
                    )
                    self._last_exit_reason = last_closed.get("exit_reason", "")
            self.position = "NONE"
            self.entry_price = 0.0
            self.sl = 0.0
            self.target1 = 0.0
            self.target2 = 0.0
            self.trade_source = "NONE"

        if signals_out:
            logger.info(
                f"[{self.strategy_id}] Generated {len(signals_out)} signals "
                f"from backtest diff ({len(bt_trades)} trades total)"
            )
        return signals_out

    # ──────────────────────────────────────────────────────────────────
    #  UI signal (for the frontend signal panel)
    # ──────────────────────────────────────────────────────────────────
    def get_ui_signal(self, cfg) -> dict:
        if self._last_exit_signal is not None:
            sig_value = self._last_exit_signal
            exit_reason = self._last_exit_reason or ""
            self._last_exit_signal = None
            self._last_exit_reason = None
        elif self.position != "NONE":
            sig_value = self.position
            exit_reason = ""
        else:
            sig_value = "HOLD"
            exit_reason = ""

        return {
            "signal": sig_value,
            "strategy": self.strategy_id,
            "time": _to_ist_iso(self.last_processed_ts) if self.last_processed_ts else "",
            "entry": round(self.entry_price, 2) if self.position != "NONE" else 0.0,
            "sl": round(self.sl, 2),
            "target1": round(self.target1, 2),
            "target2": round(self.target2, 2),
            "regime": self._regime,
            "regime_confidence": 0.0,
            "playbook": "",
            "weighted_score": 0.0,
            "atr_5m": round(self._last_atr, 2),
            "close": round(self._last_close, 2),
            "h1_trend": "",
            "macro_bias": "",
            "adx_1h": 0.0,
            "ml_prob": 0.0,
            "rr_t1": 0.0,
            "risk_pts": 0.0,
            "long_score": 0.0,
            "short_score": 0.0,
            "reasons": [exit_reason] if exit_reason else [],
            "trade_source": self.trade_source,
        }

    # ──────────────────────────────────────────────────────────────────
    #  Helpers: convert backtest trade dicts → LiveSignal objects
    # ──────────────────────────────────────────────────────────────────
    def _entry_from_trade(self, t: dict) -> LiveSignal:
        direction = t["direction"]
        return LiveSignal(
            signal_type="ENTRY",
            direction=direction,
            signal=direction,
            time=t.get("entry_time", ""),
            entry_price=round(t.get("entry_price", 0), 2),
            sl=round(t.get("sl", 0), 2),
            target1=round(t.get("target1", 0), 2),
            target2=round(t.get("target2", 0), 2),
            strategy=self.strategy_id,
            reasons=[f"Source: {t.get('source', 'STRATEGY')}"],
            regime=self._regime,
            atr_5m=round(self._last_atr, 2),
        )

    def _exit_from_trade(self, t: dict, qty: int) -> LiveSignal:
        direction = t["direction"]
        exit_signal = "LONG_EXIT" if direction == "LONG" else "SHORT_EXIT"
        return LiveSignal(
            signal_type="EXIT",
            direction=direction,
            signal=exit_signal,
            time=t.get("exit_time", ""),
            entry_price=round(t.get("entry_price", 0), 2),
            exit_price=round(t.get("exit_price", 0), 2),
            exit_reason=t.get("exit_reason", ""),
            pnl=round(t.get("pnl", 0), 2),
            pnl_pts=round(t.get("pnl_pts", 0), 2),
            sl=round(t.get("sl", 0), 2),
            strategy=self.strategy_id,
            reasons=[f"Exit: {t.get('exit_reason', '')} @ {t.get('exit_price', 0)}"],
        )


# ═══════════════════════════════════════════════════════════════════════════════
# STRATEGY-SPECIFIC PROCESSORS (thin wrappers)
# ═══════════════════════════════════════════════════════════════════════════════

class RegimeLiveProcessor(BacktestDiffProcessor):
    """Regime Trend/Range Optimized strategy."""
    strategy_id = "regime_trend_range"


class RegimeReversalLiveProcessor(BacktestDiffProcessor):
    """Regime + Reversal combined strategy."""
    strategy_id = "regime_reversal"


class MultiAgentLiveProcessor(BacktestDiffProcessor):
    """Multi-Agent V3 Kernel strategy."""
    strategy_id = "multi_agent"


class RegimeTrendV2LiveProcessor(BacktestDiffProcessor):
    """Regime Trend V2 — Selective (optimized winner)."""
    strategy_id = "regime_trend_v2"


class RegimeTrendV2BLiveProcessor(BacktestDiffProcessor):
    """Regime Trend V2-B — Balanced (runner-up)."""
    strategy_id = "regime_trend_v2b"


class DonchianSwingLiveProcessor(BacktestDiffProcessor):
    """Donchian 5m Swing (overnight-capable)."""
    strategy_id = "donchian_5m_swing"


class DonchianIntradayLiveProcessor(BacktestDiffProcessor):
    """Donchian 5m Intraday (flat by 15:15)."""
    strategy_id = "donchian_5m_intraday"


class RegimeV1FinalLiveProcessor(BacktestDiffProcessor):
    """Regime T/R V1 Final (Research) -- Donchian+CUSUM(2.0)+HTF-hold+
    SuperTrend-adaptive on the trend side, VWAP+half-life on the range
    side. Promoted to live after the scratch/research_v1/ session."""
    strategy_id = "custom_regime_v1_trend_range_final"


class HalfTrendHullLiveProcessor(BacktestDiffProcessor):
    """HalfTrend + Hull (Standalone, Research). Promoted to live after
    the scratch/research_v1/ session."""
    strategy_id = "custom_halftrend_hull_standalone"


class Cusum15LiveProcessor(BacktestDiffProcessor):
    """CUSUM 1.5 + No Donchian + CD8 (Research) -- best points/PF/net of
    the whole research session; maxDD runs ~0.9pp over the user's 7% cap,
    accepted deliberately. Promoted to live after the scratch/research_v1/
    session."""
    strategy_id = "custom_cusum15_nodonchian_cd8"


class AlphaComboLiveProcessor(BacktestDiffProcessor):
    """Alpha Combo (CUSUM 1.25 Tuned) -- CUSUM 1.5/No-Donchian/CD8 with the
    CUSUM threshold loosened to 1.25; beat the CUSUM 1.5 baseline on every
    metric in every train/validate/full window. Default live strategy,
    promoted 2026-08-22 after that strategy also beat every dual-engine
    pyramid variant tried in the same research session."""
    strategy_id = "custom_alpha_combo_cusum125"


class TimeGatedAlphaComboLiveProcessor(BacktestDiffProcessor):
    """Time-Gated Alpha Combo -- Alpha Combo with new entries blocked during
    two intraday "trap" windows (10:00-10:45 AM, 1:00-1:45 PM); existing
    positions still managed normally through those windows. Promoted to
    live 2026-08-23 after train/validate/full discipline plus a deep
    trade-level audit (chronological/overlap check, zero trap-window
    entries confirmed empirically, independent stats recompute, and a
    signal-reversal falsification test). BankNifty-only validation -- see
    STRATEGY_REGISTRY.md at the repo root."""
    strategy_id = "custom_time_gated_alpha_combo"


# ═══════════════════════════════════════════════════════════════════════════════
# SINGLETON INSTANCES — created lazily, on first use.
# Only strategies actually driven by the live loop get a processor instance;
# exploration strategies cost nothing until they are promoted to live.
# ═══════════════════════════════════════════════════════════════════════════════

_processors: Dict[str, BacktestDiffProcessor] = {}


def _get_processor(cls) -> BacktestDiffProcessor:
    p = _processors.get(cls.strategy_id)
    if p is None:
        p = cls()
        _processors[cls.strategy_id] = p
    return p


def get_regime_processor() -> RegimeLiveProcessor:
    return _get_processor(RegimeLiveProcessor)

def get_regime_reversal_processor() -> RegimeReversalLiveProcessor:
    return _get_processor(RegimeReversalLiveProcessor)

def get_multi_agent_processor() -> MultiAgentLiveProcessor:
    return _get_processor(MultiAgentLiveProcessor)

def get_regime_v2_processor() -> RegimeTrendV2LiveProcessor:
    return _get_processor(RegimeTrendV2LiveProcessor)

def get_regime_v2b_processor() -> RegimeTrendV2BLiveProcessor:
    return _get_processor(RegimeTrendV2BLiveProcessor)

def get_donchian_swing_processor() -> DonchianSwingLiveProcessor:
    return _get_processor(DonchianSwingLiveProcessor)

def get_donchian_intraday_processor() -> DonchianIntradayLiveProcessor:
    return _get_processor(DonchianIntradayLiveProcessor)

def get_regime_v1_final_processor() -> RegimeV1FinalLiveProcessor:
    return _get_processor(RegimeV1FinalLiveProcessor)

def get_halftrend_hull_processor() -> HalfTrendHullLiveProcessor:
    return _get_processor(HalfTrendHullLiveProcessor)

def get_cusum15_processor() -> Cusum15LiveProcessor:
    return _get_processor(Cusum15LiveProcessor)

def get_alpha_combo_processor() -> AlphaComboLiveProcessor:
    return _get_processor(AlphaComboLiveProcessor)

def get_time_gated_alpha_combo_processor() -> TimeGatedAlphaComboLiveProcessor:
    return _get_processor(TimeGatedAlphaComboLiveProcessor)

def reset_all_processors():
    """Reset the processors that are actually in use — call at daily boundary."""
    for p in _processors.values():
        p.reset()
